# -*- coding: utf-8 -*-
"""mnist.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DZxcTUv0uxNVvj4nu-JzB2_fQCvu2FMW
"""

import tensorflow as tf
import sys
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image, ImageOps

mnist = tf.keras.datasets.mnist

(x_train,y_train),(x_test,y_test) = mnist.load_data()

x_train = x_train.reshape((x_train.shape[0], 28, 28, 1)).astype('float32')
x_test = x_test.reshape((x_test.shape[0], 28, 28, 1)).astype('float32')

x_train = x_train / 255
x_test = x_test / 255

y_train = tf.keras.utils.to_categorical(y_train,10)
y_test = tf.keras.utils.to_categorical(y_test,10)

model = tf.keras.models.Sequential([

    tf.keras.layers.Conv2D(32, (3,3), activation = "relu", input_shape = (28, 28, 1)),

        tf.keras.layers.MaxPooling2D(pool_size = (2,2)),

        tf.keras.layers.Flatten(),

        tf.keras.layers.Dense(128, activation = "relu"),

        tf.keras.layers.Dropout(0.5),

        tf.keras.layers.Dense(10, activation = "softmax"),
        tf.keras.layers.Dense(10, activation = "softmax")


])

model.compile(
    optimizer = "adam",
    loss = "categorical_crossentropy",
    metrics = ["accuracy"]

  )


model.fit(x_train,y_train, epochs = 10)
model.evaluate(x_test,y_test, verbose = 2)

model.save("mnist_model.h5")
print("Model saved as mnist_model.h5")

from google.colab import files
uploaded = files.upload()

from PIL import Image
import numpy as np

image_path = list(uploaded.keys())[0]
img = Image.open(image_path).convert('L')

img = img.resize((28, 28))
img = np.invert(img)
img = np.array(img) / 255.0
img = img.reshape(1, 28, 28, 1)

from tensorflow.keras.models import load_model

mnist_model = load_model('mnist_model.h5')

prediction = mnist_model.predict(img)
predicted_digit = np.argmax(prediction)

print(f"Predicted digit: {predicted_digit}")